spring.application.name=Business Analytics Dashboard System
spring.datasource.url=jdbc:mysql://localhost:3306/business_db
spring.datasource.username=root
spring.datasource.password=Imasha@200304

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true